///////////////////////////////////////////////////////////////////////////
// investigator_code.js
//  This file implements the Investment Investigator web app.  The purpose
//  of this app is to help users find the best savings account for their
//  needs and to calculate how much they need to save each month to reach
//  their investment goals.
//
//  Oliver Emerson - 2025-2026
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Global Variables
///////////////////////////////////////////////////////////////////////////

// Standard Accounts data arrays
let standardAccounts = null;
let standardAccountsBankNames = null;
let standardAccountsBankAccounts = null;
let standardAccountsBankRates = null;
let standardAccountsBankCompoundings = null;
let standardAccountsBankFees = null;
let standardAccountsMinimumDeposits = null;
// CD Accounts data arrays
let cDAccounts = null;
let cDAccountsBankNames = null;
let cDAccountsBankAccounts = null;
let cDAccountsBankRates = null;
let cDAccountsBankCompoundings = null;
let cDAccountsBankFees = null;
let cDAccountsMinimumDeposits = null;
// Calculation variables
let fixedRatesStatus = null
let bankFound = null;
let isCD = null;
let payment = null;
let finalBank = null;
let finalAccount = null;
let finalRate = null;
let finalCompounding = null;
let finalFee = null;
let finalMinimumDeposit = null;
//Savings Plan Graph Variables
let userChoice = null;
let chosenCanvas = null;
// List variables for filtering - Initialized to the full lists, then filtered down based on user input
let filteredStandardAccountsBankNames = null;
let filteredStandardAccountsBankAccounts = null;
let filteredStandardAccountsBankRates = null;
let filteredStandardAccountsBankCompoundings = null;
let filteredStandardAccountsBankFees = null;
let filteredStandardAccountsMinimumDeposits = null;

let filteredCDAccountsBankNames = null;
let filteredCDAccountsBankAccounts = null;
let filteredCDAccountsBankRates = null;
let filteredCDAccountsBankCompoundings = null;
let filteredCDAccountsBankFees = null;
let filteredCDAccountsMinimumDeposits = null;



///////////////////////////////////////////////////////////////////////////
// Data Handling Functions
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
//  Function: generateSavingsCSV
//  Inputs: input - The prompt to send to the AI to generate the CSV data
//  Outputs: String - The raw CSV text generated by the AI
//  Error Checking: None
//  Summary: Sends a prompt to the Groq API to generate a CSV file based on 
// the input, and returns the raw CSV text. The function uses the fetch API 
// to make a POST request to the Groq API endpoint, including the necessary 
// headers and body with the prompt. It then processes the response to 
// extract and return the CSV content.
///////////////////////////////////////////////////////////////////////////

async function generateSavingsCSV(input) {
  const apiKey = "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";

  const prompt = input;

  const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: "llama-3.1-8b-instant",
      messages: [
        { role: "user", content: prompt }
      ]
    })
  });

  const data = await response.json();
  console.log("Groq CSV response:", data);

  if (!data.choices) {
    throw new Error("Groq error: " + JSON.stringify(data, null, 2));
  }

  const csv = data.choices[0].message.content.trim();
  return csv;
}


///////////////////////////////////////////////////////////////////////////
//  Function: readCSV
//  Inputs: url - File path/URL to CSV file
//  Outputs: Array of objects read from the CSV file
//  Error Checking: None
//  Summary: Reads a CSV file from the specified URL and returns an array 
//     of objects, where each object represents a row in the CSV file with 
// keys corresponding to the column headers.
///////////////////////////////////////////////////////////////////////////
async function readCSV(url) {
  // Read from file
  const res = await fetch(url);
  const text = await res.text();

  // Add rows for each line, split by commas
  const lines = text.trim().split("\n");
  // Get headers from first line
  // const headers = lines[0].split(",");
  const headers = lines[0]
  .split(",")
  .map(h => h.replace(/\r/g, "").trim());

  // Create an array with objects for each line, with keys from headers and values from the line
  return lines.slice(1).map(line => {
    const values = line.split(",");
    const obj = {};
    headers.forEach((h, i) => {
      obj[h] = values[i];
    });
    return obj;
  });
}


///////////////////////////////////////////////////////////////////////////
//  Function: readCSVFromAI
//  Inputs: url - The prompt to send to the AI to generate the CSV data
//  Outputs: Array of objects read from the AI generated CSV file
//  Error Checking: None
//  Summary: Sends a prompt to the Groq API to generate a CSV file based on 
// the input, reads the raw CSV text, and returns an array of objects 
// representing the rows in the CSV file. Each object has keys 
// corresponding to the column headers and values corresponding to the data 
// in each row.
///////////////////////////////////////////////////////////////////////////

async function readCSVFromAI(input) {
  const csvText = await generateSavingsCSV(input);

  const lines = csvText.trim().split("\n");

  // Hardcode the expected headers instead of reading from AI output
  const headers = ["id", "Bank", "Account Name", "Interest (Decimal)", "Compoundings per Year", "Monthly Fees", "Minimum Deposit"];

  // Check if first line looks like a header row and skip it if so
  const firstLine = lines[0].toLowerCase();
  const dataLines = firstLine.includes("bank") ? lines.slice(1) : lines;

  return dataLines.map(line => {
    const values = line.split(",");
    const obj = {};
    headers.forEach((h, i) => {
      obj[h] = values[i]?.trim();
    });
    return obj;
  });
}

///////////////////////////////////////////////////////////////////////////
//  Function: readStandardAccountsFromFile
//  Inputs: None
//  Outputs: Writes the Standard Accounts data from the CSV file to global
//    variables
//  Error Checking: None
//  Summary: Inputs the Standard Accounts data from the CSV file and
//    stores it in variables for use in the app. Also converts the table
//    into lists to match Code.org format.
///////////////////////////////////////////////////////////////////////////

async function readStandardAccountsFromFile() {
  console.log("Reading Standard Accounts...");
  standardAccounts = await readCSV("StandardAccounts.csv");
  console.log("Now it's safe to use:", standardAccounts);
  //   Convert table into lists to match Code.org format
  standardAccountsBankNames = getColumn(standardAccounts, "Bank");
  standardAccountsBankAccounts = getColumn(standardAccounts, "Account Name");
  standardAccountsBankRates = getColumn(standardAccounts, "Interest (Decimal)").map(Number);
  standardAccountsBankCompoundings = getColumn(standardAccounts, "Compoundings per Year").map(Number);
  standardAccountsBankFees = getColumn(standardAccounts, "Monthly Fees").map(Number);
  standardAccountsMinimumDeposits = getColumn(standardAccounts, "Minimum Deposit").map(Number);
  filteredStandardAccountsBankNames = standardAccountsBankNames;
  filteredStandardAccountsBankAccounts = standardAccountsBankAccounts;
  filteredStandardAccountsBankRates = standardAccountsBankRates;
  filteredStandardAccountsBankCompoundings = standardAccountsBankCompoundings;
  filteredStandardAccountsBankFees = standardAccountsBankFees;
  filteredStandardAccountsMinimumDeposits = standardAccountsMinimumDeposits;
}

///////////////////////////////////////////////////////////////////////////
//  Function: readStandardAccountsFromAI
//  Inputs: None
//  Outputs: Writes the Standard Accounts data from the AI generated CSV to global
//    variables
//  Error Checking: None
//  Summary: Inputs the Standard Accounts data from the AI generated CSV and
//    stores it in variables for use in the app. Also converts the table
//    into lists to match Code.org format.
///////////////////////////////////////////////////////////////////////////
async function readStandardAccountsFromAI() {
  console.log("Reading Standard Accounts...");
  standardAccounts = await readCSVFromAI(`
Create a data table for all the interest-bearing accounts for the top 25 standard savings accounts in the U.S. 
Include only standard savings accounts, not promotional accounts.

Format the output EXACTLY like a Code.org data table.

Use these EXACT column headers in this EXACT order:
id,Bank,Account Name,Interest (Decimal),Compoundings per Year,Monthly Fees,Minimum Deposit

Rules:
- The first column must be "id" starting at 1 and increasing by 1 for each row.
- All interest values must be decimals (e.g., 0.0365).
- All numeric fields must contain only numbers (no dollar signs, no commas).
- Return ONLY raw CSV text. 
- Do NOT include explanations, markdown, or code fences.
- Do NOT use commas within any field value. Use a slash or space instead (e.g. "Bus./Cmp. Savings" not "Bus., Cmp. Savings").

Return ONLY a CSV file. The very first line MUST be the header row: id,Bank,Account Name,Interest (Decimal),Compoundings per Year,Monthly Fees,Minimum Deposit
Do not include explanations, markdown, or code fences. Output raw CSV text only.
`);
  console.log("Now it's safe to use:", standardAccounts);
  //   Convert table into lists to match Code.org format
  standardAccountsBankNames = getColumn(standardAccounts, "Bank");
  standardAccountsBankAccounts = getColumn(standardAccounts, "Account Name");
  standardAccountsBankRates = getColumn(standardAccounts, "Interest (Decimal)").map(Number);
  standardAccountsBankCompoundings = getColumn(standardAccounts, "Compoundings per Year").map(Number);
  standardAccountsBankFees = getColumn(standardAccounts, "Monthly Fees").map(Number);
  standardAccountsMinimumDeposits = getColumn(standardAccounts, "Minimum Deposit").map(Number);
  filteredStandardAccountsBankNames = standardAccountsBankNames;
  filteredStandardAccountsBankAccounts = standardAccountsBankAccounts;
  filteredStandardAccountsBankRates = standardAccountsBankRates;
  filteredStandardAccountsBankCompoundings = standardAccountsBankCompoundings;
  filteredStandardAccountsBankFees = standardAccountsBankFees;
  filteredStandardAccountsMinimumDeposits = standardAccountsMinimumDeposits;
}

///////////////////////////////////////////////////////////////////////////
//  Function: readCDAccountsFromFile
//  Inputs: None
//  Outputs: Writes the CD Accounts data from the CSV file to global
//    variables
//  Error Checking: None
//  Summary: Inputs the CD Accounts data from the CSV file and
//    stores it in variables for use in the app. Also converts the table
//    into lists to match Code.org format.
///////////////////////////////////////////////////////////////////////////
async function readCDAccountsFromFile() {
  console.log("Reading CD Accounts...");
  cDAccounts = await readCSV("CDAccounts.csv");
  console.log("Now it's safe to use:", cDAccounts);
  //   Convert table into lists to match Code.org format
  cDAccountsBankNames = getColumn(cDAccounts, "Bank");
  cDAccountsBankAccounts = getColumn(cDAccounts, "Account Name");
  cDAccountsBankRates = getColumn(cDAccounts, "Interest (Decimal)").map(Number);
  cDAccountsBankCompoundings = getColumn(cDAccounts, "Compoundings per Year").map(Number);
  cDAccountsBankFees = getColumn(cDAccounts, "Monthly Fees").map(Number);
  cDAccountsMinimumDeposits = getColumn(cDAccounts, "Minimum Deposit").map(Number);
  filteredCDAccountsBankNames = cDAccountsBankNames;
  filteredCDAccountsBankAccounts = cDAccountsBankAccounts;
  filteredCDAccountsBankRates = cDAccountsBankRates;
  filteredCDAccountsBankCompoundings = cDAccountsBankCompoundings;
  filteredCDAccountsBankFees = cDAccountsBankFees;
  filteredCDAccountsMinimumDeposits = cDAccountsMinimumDeposits;
}

///////////////////////////////////////////////////////////////////////////
//  Function: readCDAccountsFromAI
//  Inputs: None
//  Outputs: Writes the CD Accounts data from the AI generated CSV to global
//    variables
//  Error Checking: None
//  Summary: Inputs the CD Accounts data from the AI generated CSV and
//    stores it in variables for use in the app. Also converts the table
//    into lists to match Code.org format.
///////////////////////////////////////////////////////////////////////////
async function readCDAccountsFromAI() {
  console.log("Reading CD Accounts...");
  cDAccounts = await readCSVFromAI(`
Create a data table for all the interest-bearing accounts for the top 25 CD accounts in the U.S. 
Include only CD accounts, not promotional accounts or regular savings accounts.

Format the output EXACTLY like a Code.org data table.

Use these EXACT column headers in this EXACT order:
id,Bank,Account Name,Interest (Decimal),Compoundings per Year,Monthly Fees,Minimum Deposit

Rules:
- The first column must be "id" starting at 1 and increasing by 1 for each row.
- All interest values must be decimals (e.g., 0.0365).
- All numeric fields must contain only numbers (no dollar signs, no commas).
- Return ONLY raw CSV text. 
- Do NOT include explanations, markdown, or code fences.
- Do NOT use commas within any field value. Use a slash or space instead (e.g. "Bus./Cmp. Savings" not "Bus., Cmp. Savings").

Return ONLY a CSV file. The very first line MUST be the header row: id,Bank,Account Name,Interest (Decimal),Compoundings per Year,Monthly Fees,Minimum Deposit
Do not include explanations, markdown, or code fences. Output raw CSV text only.
`);
  console.log("Now it's safe to use:", cDAccounts);
  //   Convert table into lists to match Code.org format
  cDAccountsBankNames = getColumn(cDAccounts, "Bank");
  cDAccountsBankAccounts = getColumn(cDAccounts, "Account Name");
  cDAccountsBankRates = getColumn(cDAccounts, "Interest (Decimal)").map(Number);
  cDAccountsBankCompoundings = getColumn(cDAccounts, "Compoundings per Year").map(Number);
  cDAccountsBankFees = getColumn(cDAccounts, "Monthly Fees").map(Number);
  cDAccountsMinimumDeposits = getColumn(cDAccounts, "Minimum Deposit").map(Number);
  filteredCDAccountsBankNames = cDAccountsBankNames;
  filteredCDAccountsBankAccounts = cDAccountsBankAccounts;
  filteredCDAccountsBankRates = cDAccountsBankRates;
  filteredCDAccountsBankCompoundings = cDAccountsBankCompoundings;
  filteredCDAccountsBankFees = cDAccountsBankFees;
  filteredCDAccountsMinimumDeposits = cDAccountsMinimumDeposits;
}

///////////////////////////////////////////////////////////////////////////
//  Function: startInvestigator 
//  Inputs: None
//  Outputs: None
//  Error Checking: None - Should only be called after data is loaded.
//  Summary: Startup function for the app.  Configures UI. 
///////////////////////////////////////////////////////////////////////////
function startInvestigator() {
  console.log("App started");
  // Saving Plan button actions
  onEvent("interestButton", "click", function () {
    setScreen("interestScreen");
  });
}

///////////////////////////////////////////////////////////////////////////
//  Function: initialize 
//  Inputs: None
//  Outputs: Writes all data to global variables and starts the app
//  Error Checking: None - Should only be called after data is loaded.
//  Summary: Startup function for the app.  Configures UI. 
///////////////////////////////////////////////////////////////////////////
async function initialize() {
  console.log("Reading file data...");
  await readStandardAccountsFromFile();
  await readCDAccountsFromFile();
  console.log("File reading complete.  Starting app...");
  startInvestigator();
}

///////////////////////////////////////////////////////////////////////////
// Check Valid Input Functions
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
//  Function: Check Bank Input
//  Inputs: condition - The bank name to check for in the lists
//  Outputs: Writes to global variable bankFound to indicate if the bank was found in the lists
//  Error Checking: None - Should only be called after data is loaded.
//  Summary: Checks if the specified bank name is found in the filtered lists 
// of bank names for either standard accounts or CD accounts, depending on the fixedRatesStatus. 
// Sets the global variable bankFound to true if the bank is found, and false otherwise.
///////////////////////////////////////////////////////////////////////////
function checkBankInput(condition) {
  bankFound = false;
  if (fixedRatesStatus == false) {
    for (i = 0; i < filteredStandardAccountsBankNames.length; i++) {
      if (filteredStandardAccountsBankNames[i] == condition) {
        bankFound = true;
        return;
      }
    }
  } else if (fixedRatesStatus == true) {
    for (i = 0; i < filteredCDAccountsBankNames.length; i++) {
      if (filteredCDAccountsBankNames[i] == condition) {
        bankFound = true;
        return;
      } 
    }
  }
}

///////////////////////////////////////////////////////////////////////////
//  Function: Check Input
//  Inputs: input - The string input to check for validity as a number
//  Outputs: Returns true if the input is a valid number, false otherwise
//  Error Checking: None - Should only be called after data is loaded.
//  Summary: Checks if the specified input is a valid number.
///////////////////////////////////////////////////////////////////////////
function checkInput(input) {
       if (/[^0-9]/.test(input) || input == "") {
           return false;
       } else {
           return true;
       }
}


///////////////////////////////////////////////////////////////////////////
// Search Functions
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
//  Function: Find Closest Bank
//  Inputs: None
//  Outputs: The name of the bank that matches the user input most closely, 
// or null if no match is found
//  Summary: Finds the bank name in the lists that best matches the user 
// input in the search bar, using a combination of substring matching, 
// word-level matching, and Levenshtein distance for fuzzy matching. 
// Returns the name of the closest matching bank, or null if no match is found.
///////////////////////////////////////////////////////////////////////////
function findClosestBank(input) {
  const userInput = document.getElementById(input).value.trim().toLowerCase();
  if (!userInput) return null;

  const allBanks = [...standardAccountsBankNames, ...cDAccountsBankNames];

  let bestMatch = null;
  let bestScore = -Infinity;

  for (const bank of allBanks) {
    const lower = bank.toLowerCase();
    let score = 0;

    // Substring priority
    if (lower.includes(userInput)) score += 1000;

    // Word-level matching
    const inputWords = userInput.split(" ");
    const bankWords = lower.split(" ");
    for (const iw of inputWords) {
      for (const bw of bankWords) {
        if (bw === iw) score += 150;
        else if (bw.startsWith(iw)) score += 50;
      }
    }

    // Levenshtein fallback
    score -= levenshtein(userInput, lower);

    if (score > bestScore) {
      bestScore = score;
      bestMatch = bank;
    }
  }

  return bestMatch;
}

///////////////////////////////////////////////////////////////////////////
//  Function: Find Closest Account for Bank
//  Inputs: bankName - The output of findClosestBank
//  Outputs: The name of the account that matches the user input most closely, 
// or null if no match is found. Uses only accounts that are from the bank 
// outputted by findClosestBank.
//  Summary: Finds the account name in the lists that best matches the user 
// input in the search bar, using a combination of substring matching, 
// word-level matching, and Levenshtein distance for fuzzy matching.
///////////////////////////////////////////////////////////////////////////
function findClosestAccountForBank(bankName, input) {
  const userInput = getText(input);

  // Build restricted list
  const accounts = [];

  // Standard accounts
  for (let i = 0; i < standardAccountsBankNames.length; i++) {
    if (standardAccountsBankNames[i] === bankName) {
      accounts.push({
        name: standardAccountsBankAccounts[i],
        index: i,
        isCD: false
      });
    }
  }

  // CD accounts
  for (let i = 0; i < cDAccountsBankNames.length; i++) {
    if (cDAccountsBankNames[i] === bankName) {
      accounts.push({
        name: cDAccountsBankAccounts[i],
        index: i,
        isCD: true
      });
    }
  }

  // Fuzzy match within this bank’s accounts
  let best = null;
  let bestScore = -Infinity;

  for (const acc of accounts) {
    const lower = acc.name.toLowerCase();
    let score = 0;

    if (lower.includes(userInput)) score += 1000;

    const inputWords = userInput.split(" ");
    const accWords = lower.split(" ");
    for (const iw of inputWords) {
      for (const aw of accWords) {
        if (aw === iw) score += 150;
        else if (aw.startsWith(iw)) score += 50;
      }
    }

    score -= levenshtein(userInput, lower);

    if (score > bestScore) {
      bestScore = score;
      best = acc;
    }
  }

  return best; // { name, index, isCD }
}

///////////////////////////////////////////////////////////////////////////
//  Function: Find Best Match
//  Inputs: None
//  Outputs: The index and type (CD or standard) of the account that matches 
// the user input most closely, or null if no match is found. Uses only 
// accounts that are from the bank outputted by findClosestBank.
//  Summary: Finds the account that best matches the user input in the search bar.
///////////////////////////////////////////////////////////////////////////
function findBestMatch(input) {
  const bank = findClosestBank(input);
  if (!bank) return null;

  return findClosestAccountForBank(bank, input);
}


function searchOutput() {
  const result = findBestMatch("browseAccountsSearchBar");
  if (!result) {
    setText("browseAccountsSearchOutput", "No matching account found.");
    return;
  }

  const { index, isCD } = result;

  if (isCD) {
    setText("browseAccountsSearchOutput",
      "Bank: " + cDAccountsBankNames[index] + "\n" +
      "Account Name: " + cDAccountsBankAccounts[index] + "\n" +
      "Interest Rate: " + Math.round(cDAccountsBankRates[index] * 10000) / 100 + "%\n" +
      "Compoundings per Year: " + cDAccountsBankCompoundings[index] + "\n" +
      "Monthly Fees: $" + cDAccountsBankFees[index] + "\n" +
      "Minimum Deposit: $" + cDAccountsMinimumDeposits[index]
    );
  } else {
    setText("browseAccountsSearchOutput",
      "Bank: " + standardAccountsBankNames[index] + "\n" +
      "Account Name: " + standardAccountsBankAccounts[index] + "\n" +
      "Interest Rate: " + Math.round(standardAccountsBankRates[index] * 10000)/100 + "%\n" +
      "Compoundings per Year: " + standardAccountsBankCompoundings[index] + "\n" +
      "Monthly Fees: $" + standardAccountsBankFees[index] + "\n" +
      "Minimum Deposit: $" + standardAccountsMinimumDeposits[index]
    );
  }
}


///////////////////////////////////////////////////////////////////////////
// Calculation Functions
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
//  Function: Calculate Savings Plan
//  Inputs: None
//  Outputs: Final account information and interactive principal to deposit 
// amount graph
//  Summary: Applies account filters and findMax() function to narrow account 
// selection down to a single account and then uses the account information to 
// create an interactive graph where users can choose a custom principal to 
// recurring deposit amount ratio
///////////////////////////////////////////////////////////////////////////
function calculateSavingsPlan() {
  setScreen("savingsPlanOutputScreen");
  const points = null;

  if (getText("savingsPlanFixedRatesInput") == "No") {
    fixedRatesStatus = false;
  } else if (getText("savingsPlanFixedRatesInput") == "Yes") {
    fixedRatesStatus = true;
  }
  monthlyFeesFilter("savingsPlanMonthlyFeesInput");
  minimumDepositFilter("savingsPlanMinimumDepositInput");
  bankFilter("savingsPlanPreferredBankInput");


  findMax(1000, getNumber("savingsPlanInvestmentLengthInput"));

  drawInteractiveSavingsPlan(
    getNumber("savingsPlanInvestmentGoalInput"),
    getNumber("savingsPlanInvestmentLengthInput"),
    finalRate,
    finalCompounding,
    getNumber("savingsPlanDepositFrequencyInput"),
    function (point) {
      // This captures the user's click
      userChoice = point;
      console.log("Selected Point:", point);
    }
  );

  filteredStandardAccountsBankNames = standardAccountsBankNames;
  filteredStandardAccountsBankAccounts = standardAccountsBankAccounts;
  filteredStandardAccountsBankRates = standardAccountsBankRates;
  filteredStandardAccountsBankCompoundings = standardAccountsBankCompoundings;
  filteredStandardAccountsBankFees = standardAccountsBankFees;
  filteredStandardAccountsMinimumDeposits = standardAccountsMinimumDeposits;
  filteredCDAccountsBankNames = cDAccountsBankNames;
  filteredCDAccountsBankAccounts = cDAccountsBankAccounts;
  filteredCDAccountsBankRates = cDAccountsBankRates;
  filteredCDAccountsBankCompoundings = cDAccountsBankCompoundings;
  filteredCDAccountsBankFees = cDAccountsBankFees;
  filteredCDAccountsMinimumDeposits = cDAccountsMinimumDeposits;
}

///////////////////////////////////////////////////////////////////////////
//  Function: Find An Account
//  Inputs: None
//  Outputs: Final account information and graph showing projected savings 
// growth
//  Summary: Applies account filters and findMax() function to narrow account 
// selection down to a single account and then uses the account information to 
// fill out an output text area and create a graph showing projected savings growth
///////////////////////////////////////////////////////////////////////////
function findAnAccount() {
  if (getText("findAccountsFixedRatesInput") == "No") {
    fixedRatesStatus = false;
  } else if (getText("findAccountsFixedRatesInput") == "Yes") {
    fixedRatesStatus = true;
  }

  monthlyFeesFilter("findAccountsMonthlyFeesInput");

  minimumDepositFilter("findAccountsMinimumDepositInput");

  bankFilter("findAccountsPreferredBankInput");

  findMax(getNumber("findAccountsPrincipalInput"), getNumber("findAccountsInvestmentLengthInput"));
  // calculatePayment(getNumber("savingsPlanInvestmentGoalInput"), getNumber("savingsPlanPrincipalInput"), getNumber("savingsPlanInvestmentLengthInput"), getNumber("savingsPlanDepositFrequencyInput"));
  findAnAccountOutput();
  
  chosenCanvas = "interestCanvas";
  const points = computeGrowth(getNumber("findAccountsPrincipalInput"), finalRate, finalCompounding, getNumber("findAccountsInvestmentLengthInput"));
  drawGraph(points);

  filteredStandardAccountsBankNames = standardAccountsBankNames;
  filteredStandardAccountsBankAccounts = standardAccountsBankAccounts;
  filteredStandardAccountsBankRates = standardAccountsBankRates;
  filteredStandardAccountsBankCompoundings = standardAccountsBankCompoundings;
  filteredStandardAccountsBankFees = standardAccountsBankFees;
  filteredStandardAccountsMinimumDeposits = standardAccountsMinimumDeposits;
  filteredCDAccountsBankNames = cDAccountsBankNames;
  filteredCDAccountsBankAccounts = cDAccountsBankAccounts;
  filteredCDAccountsBankRates = cDAccountsBankRates;
  filteredCDAccountsBankCompoundings = cDAccountsBankCompoundings;
  filteredCDAccountsBankFees = cDAccountsBankFees;
  filteredCDAccountsMinimumDeposits = cDAccountsMinimumDeposits;

}

///////////////////////////////////////////////////////////////////////////
//  Function: Find An Account Output
//  Inputs: None
//  Outputs: Final account information summarized in an output text area
//  Summary: Uses final account infomration/variables to write a summary
//about the app's suggested account in an output text area
///////////////////////////////////////////////////////////////////////////
function findAnAccountOutput() {
  setText("findAccountsOutput", 
    "Investment Investigator suggests the " + finalAccount + " at " + finalBank + 
    " with an interest rate of " + Math.round(finalRate * 1000)/10 + "%, compounded " + finalCompounding + 
    " times per year. It has monthly fees of $" + finalFee + " and a minimum deposit of $"
     + finalMinimumDeposit + ". After " + getNumber("findAccountsInvestmentLengthInput") + 
     " years, your initial deposit of $" + getNumber("findAccountsPrincipalInput") + " will grow to $" + 
     findMax(getNumber("findAccountsPrincipalInput"), getNumber("findAccountsInvestmentLengthInput")) + "."
    );
}

///////////////////////////////////////////////////////////////////////////
//  Function: compareTwoAccountsGrowth
//  Inputs: None
//  Outputs: Draws a dual‑line growth graph on the Compare Rates canvas
//  Summary: Reads two user‑entered account names, resolves each one using
//    the app’s fuzzy search system, and extracts their interest rate and
//    compounding information. It then computes compound‑interest growth
//    curves for both accounts over the user‑selected principal and time
//    period. Finally, it displays the results together on a dual graph so
//    users can visually compare long‑term performance.
///////////////////////////////////////////////////////////////////////////
function compareTwoAccountsGrowth() {
  // Read user inputs
  const input1 = "compareRatesAccount1Input";
  const input2 = "compareRatesAccount2Input";

  const text1 = getText(input1).trim();
  const text2 = getText(input2).trim();

  if (!text1 || !text2) {
    console.warn("Both account inputs are required.");
    return;
  }



  function resolveAccount(inputId) {
    const result = findBestMatch(inputId);  
    if (!result) return null;

    const { index, isCD } = result;

    if (isCD) {
      return {
        rate: cDAccountsBankRates[index],
        comp: cDAccountsBankCompoundings[index],
        bank: cDAccountsBankNames[index],
        account: cDAccountsBankAccounts[index]
      };
    } else {
      return {
        rate: standardAccountsBankRates[index],
        comp: standardAccountsBankCompoundings[index],
        bank: standardAccountsBankNames[index],
        account: standardAccountsBankAccounts[index]
      };
    }
  }

  const acc1 = resolveAccount(input1);
  const acc2 = resolveAccount(input2);

  if (!acc1 || !acc2) {
    console.warn("One or both accounts could not be resolved.");
    return;
  }

  const principal = getNumber("compareRatesPrincipalInput");   
  const years = getNumber("compareRatesLengthInput");  

  const pointsA = computeGrowth(principal, acc1.rate, acc1.comp, years);
  const pointsB = computeGrowth(principal, acc2.rate, acc2.comp, years);

  drawDualGraph(pointsA, pointsB, acc1.account, acc2.account);

}

///////////////////////////////////////////////////////////////////////////
//  Function: explainCompareRates
//  Inputs: None
//  Outputs: Writes a textual explanation to the Compare Rates output area
//  Summary: Reads two user‑entered account names, resolves each one using
//    the app’s fuzzy search system, and extracts their bank, rate, and
//    compounding information. It then computes each account’s compound‑
//    interest growth over the user‑selected principal and time period,
//    compares their final values, and generates a written explanation
//    indicating which account performs better and why.
///////////////////////////////////////////////////////////////////////////
function explainCompareRates() {
  const input1 = "compareRatesAccount1Input";
  const input2 = "compareRatesAccount2Input";

  const text1 = getText(input1).trim();
  const text2 = getText(input2).trim();

  if (!text1 || !text2) {
    setText("compareRatesOutput", "Please enter two account names to compare.");
    return;
  }

  const acc1 = findBestMatch(input1);
  const acc2 = findBestMatch(input2);

  if (!acc1 || !acc2) {
    setText("compareRatesOutput", "One or both accounts could not be found.");
    return;
  }

  const a = acc1.isCD
    ? {
        bank: cDAccountsBankNames[acc1.index],
        account: cDAccountsBankAccounts[acc1.index],
        rate: cDAccountsBankRates[acc1.index],
        comp: cDAccountsBankCompoundings[acc1.index]
      }
    : {
        bank: standardAccountsBankNames[acc1.index],
        account: standardAccountsBankAccounts[acc1.index],
        rate: standardAccountsBankRates[acc1.index],
        comp: standardAccountsBankCompoundings[acc1.index]
      };

  const b = acc2.isCD
    ? {
        bank: cDAccountsBankNames[acc2.index],
        account: cDAccountsBankAccounts[acc2.index],
        rate: cDAccountsBankRates[acc2.index],
        comp: cDAccountsBankCompoundings[acc2.index]
      }
    : {
        bank: standardAccountsBankNames[acc2.index],
        account: standardAccountsBankAccounts[acc2.index],
        rate: standardAccountsBankRates[acc2.index],
        comp: standardAccountsBankCompoundings[acc2.index]
      };

  const principal = getNumber("compareRatesPrincipalInput");   
  const years = getNumber("compareRatesLengthInput"); 

  const pointsA = computeGrowth(principal, a.rate, a.comp, years);
  const pointsB = computeGrowth(principal, b.rate, b.comp, years);

  const finalA = pointsA[pointsA.length - 1];
  const finalB = pointsB[pointsB.length - 1];

  let message = "";

  if (finalA > finalB) {
    message =
      `Investment Investigator suggests ${a.account} at ${a.bank} because it ends with $${finalA.toFixed(0)}, ` +
      `which is higher than ${b.account} at ${b.bank}, ` +
      `which ends with $${finalB.toFixed(0)}.\n\n` +
      `Therefore, **${a.account}** is the better choice over a ${years}-year period with a principal of $${principal}.`;
  } else if (finalB > finalA) {
    message =
      `Investment Investigator suggests ${b.account} at ${b.bank} because it ends with $${finalB.toFixed(0)}, ` +
      `which is higher than ${a.account} at ${a.bank}, ` +
      `which ends with $${finalA.toFixed(0)}.\n\n` +
      `Therefore, **${b.account}** is the better choice over a ${years}-year period with a principal of $${principal}.`;
  } else {
    message =
      `Both accounts end with the same value of $${finalA.toFixed(0)} after ${years} years.`;
  }

  setText("compareRatesOutput", message);
}


///////////////////////////////////////////////////////////////////////////
// Filter Functions
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
//  Function: findMax
//  Inputs: principal (number), time (number)
//  Outputs: Returns the highest final value among all filtered accounts
//  Summary: Iterates through either the filtered standard accounts or CD
//    accounts—depending on the fixed‑rate setting—and computes each
//    account’s final value using compound‑interest growth. Tracks the
//    account with the highest return and updates the global final account
//    variables (bank, account name, rate, compounding, fees, minimum
//    deposit). Returns the rounded maximum value for use in account
//    recommendations.
///////////////////////////////////////////////////////////////////////////
function findMax(principal, time) {
  let i;
  let max = 0;
  let temp;
  if (fixedRatesStatus == false) {
    for (i = 0; i < filteredStandardAccountsBankNames.length; i++) {
      temp = (principal * (Math.pow(1 + (filteredStandardAccountsBankRates[i] / filteredStandardAccountsBankCompoundings[i]), (filteredStandardAccountsBankCompoundings[i] * time))));
      if (temp > max) {
        max = temp;
        finalBank = filteredStandardAccountsBankNames[i];
        finalAccount = filteredStandardAccountsBankAccounts[i];
        finalRate = filteredStandardAccountsBankRates[i];
        finalCompounding = filteredStandardAccountsBankCompoundings[i];
        finalFee = filteredStandardAccountsBankFees[i];
        finalMinimumDeposit = filteredStandardAccountsMinimumDeposits[i];
      }
    }
    return Math.round(max);
  } else if (fixedRatesStatus == true) {
    for (i = 0; i < filteredCDAccountsBankNames.length; i++) {
      temp = (principal * (Math.pow(1 + (filteredCDAccountsBankRates[i] / filteredCDAccountsBankCompoundings[i]), (filteredCDAccountsBankCompoundings[i] * time))));
      if (temp > max) {
        max = temp;
        finalBank = filteredCDAccountsBankNames[i];
        finalAccount = filteredCDAccountsBankAccounts[i];
        finalRate = filteredCDAccountsBankRates[i];
        finalCompounding = filteredCDAccountsBankCompoundings[i];
        finalFee = filteredCDAccountsBankFees[i];
        finalMinimumDeposit = filteredCDAccountsMinimumDeposits[i];
      }
    }
    return Math.round(max);
  }
}

///////////////////////////////////////////////////////////////////////////
//  Function: sortList
//  Inputs: standardList (array), cDlist (array), condition (value to match)
//  Outputs: Updates the filtered account arrays based on the given condition
//  Summary: Filters either the standard‑account lists or CD‑account lists
//    depending on the fixed‑rate setting. It checks each account’s
//    corresponding filter list for a matching condition, and when matched,
//    copies that account’s bank name, account name, rate, compounding,
//    fees, and minimum deposit into temporary arrays. After processing,
//    it replaces the global filtered arrays with the narrowed‑down results,
//    effectively shrinking the active account list for further filtering.
///////////////////////////////////////////////////////////////////////////
function sortList(standardList, cDlist, condition) {
  let bankTemp = [];
  let accountTemp = [];
  let rateTemp = [];
  let compoundingTemp = [];
  let feeTemp = [];
  let depositTemp = [];
  if (fixedRatesStatus == false) {
    for (i = 0; i < filteredStandardAccountsBankNames.length; i++) {
      if (standardList[i] == condition) {
        appendItem(bankTemp, filteredStandardAccountsBankNames[i]);
        appendItem(accountTemp, filteredStandardAccountsBankAccounts[i]);
        appendItem(rateTemp, filteredStandardAccountsBankRates[i]);
        appendItem(compoundingTemp, filteredStandardAccountsBankCompoundings[i]);
        appendItem(feeTemp, filteredStandardAccountsBankFees[i]);
        appendItem(depositTemp, filteredStandardAccountsMinimumDeposits[i]);
      }
    }
    filteredStandardAccountsBankNames = bankTemp;
    filteredStandardAccountsBankAccounts = accountTemp;
    filteredStandardAccountsBankRates = rateTemp;
    filteredStandardAccountsBankCompoundings = compoundingTemp;
    filteredStandardAccountsBankFees = feeTemp;
    filteredStandardAccountsMinimumDeposits = depositTemp;
    return;
  } else if (fixedRatesStatus == true) {
    for (i = 0; i < filteredCDAccountsBankNames.length; i++) {
      if (cDlist[i] == condition) {
        appendItem(bankTemp, filteredCDAccountsBankNames[i]);
        appendItem(accountTemp, filteredCDAccountsBankAccounts[i]);
        appendItem(rateTemp, filteredCDAccountsBankRates[i]);
        appendItem(compoundingTemp, filteredCDAccountsBankCompoundings[i]);
        appendItem(feeTemp, filteredCDAccountsBankFees[i]);
        appendItem(depositTemp, filteredCDAccountsMinimumDeposits[i]);
      }
    }
    filteredCDAccountsBankNames = bankTemp;
    filteredCDAccountsBankAccounts = accountTemp;
    filteredCDAccountsBankRates = rateTemp;
    filteredCDAccountsBankCompoundings = compoundingTemp;
    filteredCDAccountsBankFees = feeTemp;
    filteredCDAccountsMinimumDeposits = depositTemp;
    return;
  }
}

///////////////////////////////////////////////////////////////////////////
//  Function: monthlyFeesFilter
//  Inputs: type (the ID of the user’s Yes/No dropdown)
//  Outputs: Optionally filters account lists based on monthly fees
//  Summary: Checks whether the user wants to filter out accounts with
//    monthly fees. If the user selects “Yes,” no filtering is applied.
//    If the user selects “No,” the function calls sortList to keep only
//    accounts whose monthly fee is zero, narrowing the active account
//    lists for further processing.
///////////////////////////////////////////////////////////////////////////
function monthlyFeesFilter(type) {
  let i;
  if (getText(type) == "Yes") {
    return;
  } else if (getText(type) == "No") {
    sortList(filteredStandardAccountsBankFees, filteredCDAccountsBankFees, 0);
  }
}

///////////////////////////////////////////////////////////////////////////
//  Function: minimumDepositFilter
//  Inputs: type (the ID of the user’s Yes/No dropdown)
//  Outputs: Optionally filters account lists based on minimum deposit
//  Summary: Determines whether the user wants to filter out accounts
//    requiring a minimum deposit. If the user selects “Yes,” the lists
//    remain unchanged. If the user selects “No,” the function calls
//    sortList to keep only accounts with a minimum deposit of zero,
//    reducing the filtered account lists for subsequent steps.
///////////////////////////////////////////////////////////////////////////
function minimumDepositFilter(type) {
  let i;
  if (getText(type) == "Yes") {
    return;
  } else if (getText(type) == "No") {
    sortList(filteredStandardAccountsMinimumDeposits, filteredCDAccountsMinimumDeposits, 0);
  }
}

///////////////////////////////////////////////////////////////////////////
//  Function: bankFilter
//  Inputs: input (the ID of the user’s preferred‑bank text field)
//  Outputs: Updates filtered account lists or displays an error message
//  Summary: Reads the user’s preferred bank name and checks whether it
//    exists in the filtered account lists using checkBankInput. If the
//    user selects “None,” all banks remain eligible. If a valid bank is
//    found, the function calls sortList to keep only accounts from that
//    bank. If no match is found, it notifies the user by replacing the
//    input text with “Bank Not Found.”
///////////////////////////////////////////////////////////////////////////
function bankFilter(input) {
  let i;
  checkBankInput(getText(input));
  if (getText(input) == "None") {
    bankFound = true;
    return;
  } else if (bankFound == true) {
    sortList(filteredStandardAccountsBankNames, filteredCDAccountsBankNames, getText(input));
  } else {
    setText(input, "Bank Not Found");
  }
}

///////////////////////////////////////////////////////////////////////////
// UI actions - Buttons
///////////////////////////////////////////////////////////////////////////

// Buttons Actions
onEvent("savingsPlanCalculateButton", "click", function () {
  hideElement("savingsPlanOutputScreenTutorial");
  calculateSavingsPlan();
  if (bankFound == true) {
    setScreen("savingsPlanOutputScreen");
  }
});

onEvent("RefreshAccounts", "click", async function () {
  await readStandardAccountsFromAI();
  await readCDAccountsFromAI();
  console.log("Data refreshed from AI.", standardAccounts, cDAccounts);
  alert("Accounts Refreshed!");
});

onEvent("findAccountsCalculateButton", "click", function () {
  findAnAccount();
  if (bankFound == true) {
    setScreen("findAccountsOutputScreen");
  } 
});

onEvent("browseAccountsSearchButton", "click", function () {
  if (getText("browseAccountsSearchBar") == "") {
    setText("browseAccountsSearchOutput", "Please enter a bank or account name to search.");
  } else {
    searchOutput();
    setScreen("browseAccountsSearchOutputScreen");
    setText("browseAccountsSearchBar", "");
  }
});

onEvent("browseAccountsSeeAllAccountsButton", "click", function () {
  renderAllAccountsTables();
  setScreen("browseAccountsAllAccountsScreen");
});

onEvent("browseAccountsCompareRatesCalculateButton", "click", function () {
  let inputCheck = true;
  if (getText("compareRatesAccount1Input") == "") {
    setText("compareRatesAccount1Input", "Please enter an account bank or key word");
    inputCheck = false;
  }
  if (getText("compareRatesAccount2Input") == "") {
    setText("compareRatesAccount2Input", "Please enter an account bank or key word");
    inputCheck = false;
  }
  if (checkInput(getNumber("compareRatesLengthInput")) == false) {
    setText("compareRatesLengthInput", "Invalid Input - Must be a whole number");
    inputCheck = false
  }
  if (checkInput(getNumber("compareRatesPrincipalInput")) == false) {
    setText("compareRatesPrincipalInput", "Invalid Input - Must be a whole number");
    inputCheck = false;
  }
  if (inputCheck == true) {
    compareTwoAccountsGrowth();
    explainCompareRates();
    setScreen("compareRatesOutputScreen");
    setText("compareRatesAccount1Input", "");
    setText("compareRatesAccount2Input", "");
    setText("compareRatesLengthInput", "");
    setText("compareRatesPrincipalInput", "");
  }

});

onEvent("confirmPointButton", "click", function () {
  if (userChoice) {

    alert("Plan Confirmed!");
    setScreen("savingsPlanSummaryScreen");
    setText("savingsPlanOutput",
      "To achieve your goal of $" + getNumber("savingsPlanInvestmentGoalInput") +
      " in " + getNumber("savingsPlanInvestmentLengthInput") +
      " years, Investment Investigator suggests investing $" + userChoice.principal.toFixed(2) + " in a " +
      finalAccount + " account at " + finalBank + " and depositing $" + userChoice.deposit.toFixed(2) + " " +
      getNumber("savingsPlanDepositFrequencyInput") + " times per year over your " +
      getNumber("savingsPlanInvestmentLengthInput") + " year savings period."
    );

    chosenCanvas = "savingsPlanOutputCanvas";
    const points = computeGrowthAdvanced(userChoice.principal, finalRate, finalCompounding, getNumber("savingsPlanInvestmentLengthInput"), userChoice.deposit, getNumber("savingsPlanDepositFrequencyInput"));
    drawGraph(points);

  } else {
    alert("Please select a point on the graph first.");
  }
});



///////////////////////////////////////////////////////////////////////////
// Start the app by initializing data and configuring UI
///////////////////////////////////////////////////////////////////////////
window.addEventListener("DOMContentLoaded", function () {
  initialize();
});
