///////////////////////////////////////////////////////////////////////////
// investigator_screen_nav.js
//  This file contains the code for navigating between screens in the 
// Investment Investigator App.
//
//  Oliver Emerson - 2026
///////////////////////////////////////////////////////////////////////////


// Event Handlers (Screen Navigation) For Global Header Buttons
onEvent("globalHelpButton", "click", function () {
  lastScreen = getScreen();
  hideElement("helpScreenOutput");
  setScreen("helpScreen");
});

onEvent("globalAboutButton", "click", function () {
  lastScreen = getScreen();
  hideElement("aboutScreenOutput");
  setScreen("aboutScreen");
});

onEvent("globalHomeButton", "click", function () {
  setScreen("homeScreen");
});

// Event Handlers (Screen Navigation) For Help Screen
let lastScreen = null;

onEvent("monthlyFeesHelpButton", "click", function () {
  showElement("helpScreenOutput");
  setText("helpScreenOutput",
    "Why Would I Want Monthly Fees? \n \n" +
    "People oftentimes choose interest-bearing accounts with monthly fees because the benefits that come with these accounts usually outweigh the cost. Accounts with monthly fees are likely to have higher interest rates, and come with special perks or features."
  );
});

onEvent("minimumDepositHelpButton", "click", function () {
  showElement("helpScreenOutput");
  setText("helpScreenOutput", 
    "Why Would I Want a Minimum Deposit? \n \n" +
    "People oftentimes choose interest-bearing accounts with a minimum deposit because the benefits that come with these accounts usually outweigh the cost. Accounts with a minimum deposit are likely to have higher interest rates, and come with access to premium account features."
  );
});

onEvent("fixedRatesHelpButton", "click", function () {
  showElement("helpScreenOutput");
  setText("helpScreenOutput",
    "Why Would I Want Fixed Rates? \n \n" + 
    "People oftentimes choose interest-bearing accounts with fixed rates (such as CD Accounts) because these accounts come with reliable stability and proctections. Accounts with fixed rates have easily predictable growth and come with protections from rate drops."
  );
});

onEvent("interestAccountsHelpButton", "click", function () {
  showElement("helpScreenOutput");
  setText("helpScreenOutput", 
    "What Are Interest-Bearing Accounts? \n \n" +
    "Interest‑bearing accounts are bank accounts that pay you money over time in the form of interest, allowing your balance to grow just by keeping funds deposited. These accounts—like savings accounts, CDs, and money market accounts—use your deposited money to help the bank lend or invest, and in return they reward you with a percentage of earnings."
  )
});

onEvent("helpScreenBackButton", "click", function () {
  setScreen(lastScreen);
});

// Event Handlers (Screen Navigation) For About Screen
onEvent("aboutScreenAboutButton", "click", function () {
  showElement("aboutScreenOutput");
  setText("aboutScreenOutput",
    "Investment Investigator is an all in one financial tool that helps users explore the potential of interest-bearing accounts. The app offers a variety of powerful features that allow users to browse a wide library of account options, find an account that matches their personal criteria, and even create a custom savings plan that utilizes interest-bearing accounts. \n \n" + 
    "By using Investment Investigator, users can gain the confidence and assistance they need to harness the power of interest-bearing accounts with just a few clicks."
  );
});

onEvent("aboutScreenV2.0Button", "click", function () {
  showElement("aboutScreenOutput");
  setText("aboutScreenOutput",
    "V2.0 Update Notes: \n \n" +
    "1.) Reworked Find Account feature from V1.0 with better account filters for personal criteria, and added graph visual showing the potential savings growth of the account Investment Investigator suggests. \n \n" + 
    "2.) Added Refresh Accounts feature which utilizes Groq API calls to refresh the app’s account data tables to contain the most recent and accurate interest rates. \n \n" +
    "3.) Added Browse Accounts feature for users who want to research their own account without using the Find Accounts Tool. Allows users to search for an account in the database or see all the accounts stored in tables. Additionally, users can use the compare accounts feature to compare 2 accounts and see which would make them more money over an inputted period of time. \n \n" +
    "4.) Added Create Savings Plan feature which allows users to create a custom savings plan that uses interest bearing accounts. Users enter a savings goal, investment period, and deposit frequency as well as account preferences and then choose a custom recurring deposit amount to principal ratio generated by the app. The app then outputs a savings plan the user can use to reach their savings goal in their chosen time frame. \n \n" +
    "5.) Updated UI for a cleaner and more organized aesthetic."
  );
});

onEvent("aboutScreenDisclaimerButton", "click", function () {
  showElement("aboutScreenOutput");
  setText("aboutScreenOutput",
    "Disclaimer: \n \n" +
    "Investment Investigator is a financial tool designed to help users explore interest‑bearing accounts and understand how savings can grow over time. The app provides general financial information, automated calculations, and AI‑generated data, but it does not offer professional financial, legal, or investment advice. Account details, interest rates, and recommendations are for learning purposes only and may not reflect real‑world offerings. Users should verify all information independently and consult a qualified financial professional before making any financial decisions. \n \n" +
    "AI Warning: \n \n" +
    "Investment Investigator uses AI generated images (title image). All data provided by the Refresh Accounts feature is AI generated and can be inaccurate. Do not trust AI generated rates until verified. Additionally, because the Refresh Accounts feature is experimental, using it can disrupt the functionality of the app."
  );
});

onEvent("aboutScreenBackButton", "click", function () {
  setScreen(lastScreen);
});

onEvent("aboutScreenVideoButton", "click", function () {
  window.open("https://youtu.be/MkREOBvqixE", "_blank");
});

// Event Handlers (Screen Navigation) For Interest Screen
onEvent("savingsPlanButton", "click", function () {
  setScreen("savingsPlanScreen1");
});

onEvent("findAnAccountButton", "click", function () {
  setScreen("findAccountsScreen1");
});

onEvent("browseAccountsButton", "click", function () {
  setScreen("browseAccountsScreen1");
});

onEvent("interestScreenBackButton", "click", function () {
  setScreen("homeScreen");
});

// Event Handlers (Screen Navigation) For Savings Plan Screen 1
onEvent("savingsPlanScreen1BackButton", "click", function () {
  setScreen("interestScreen");
});

onEvent("savingsPlanScreen1NextButton", "click", function () {
  let inputCheck = true;
  if (checkInput(getText("savingsPlanInvestmentGoalInput")) == false) {
    setText("savingsPlanInvestmentGoalInput", "Invalid Input - Must be a whole number");
    inputCheck = false;
  } 
  if (checkInput(getText("savingsPlanInvestmentLengthInput")) == false) {
    setText("savingsPlanInvestmentLengthInput", "Invalid Input - Must be a whole number");
    inputCheck = false;
  } 
  if ((checkInput(getText("savingsPlanDepositFrequencyInput")) == false) || (getNumber("savingsPlanDepositFrequencyInput") < 1 )) {
    setText("savingsPlanDepositFrequencyInput", "Invalid Input - Must be a whole number greater than 0");
    inputCheck = false;
  }

  if (inputCheck == true) {
    setText("savingsPlanPreferredBankInput", "None");
    setScreen("savingsPlanScreen2");
  }
});

// Event Handlers (Screen Navigation) For Savings Plan Screen 2
onEvent("savingsPlanScreen2BackButton", "click", function () {
  setScreen("savingsPlanScreen1");
});

onEvent("savingsPlanFixedRatesToolTip", "click", function () {
  lastScreen = getScreen();
  setText("helpScreenOutput",
    "Why Would I Want Fixed Rates? \n \n" +
    "People oftentimes choose interest-bearing accounts with fixed rates (such as CD Accounts) because these accounts come with reliable stability and proctections. Accounts with fixed rates have easily predictable growth and come with protections from rate drops."
  );
  setScreen("helpScreen");
});

onEvent("savingsPlanMonthlyFeesToolTip", "click", function () {
  lastScreen = getScreen();
  setText("helpScreenOutput",
    "Why Would I Want Monthly Fees? \n \n" +
    "People oftentimes choose interest-bearing accounts with monthly fees because the benefits that come with these accounts usually outweigh the cost. Accounts with monthly fees are likely to have higher interest rates, and come with special perks or features."
  );
  setScreen("helpScreen");
});

onEvent("savingsPlanMinimumDepositToolTip", "click", function () {
  lastScreen = getScreen();
  setText("helpScreenOutput", 
    "Why Would I Want a Minimum Deposit? \n \n" +
    "People oftentimes choose interest-bearing accounts with a minimum deposit because the benefits that come with these accounts usually outweigh the cost. Accounts with a minimum deposit are likely to have higher interest rates, and come with access to premium account features."
  );
  setScreen("helpScreen");
});

// Event Handlers (Screen Navigation) For Savings Plan Output Screen
onEvent("savingsPlanOutputScreenToolTip", "click", function () {
  showElement("savingsPlanOutputScreenTutorial");
  setText("savingsPlanOutputScreenTutorial", 
    "The graph above represents the trade-off between the principal and recurring deposit amount you need to reach your savings goal of $" + getNumber("savingsPlanInvestmentGoalInput") + " within " + getNumber("savingsPlanInvestmentLengthInput") + " years. Interact with the graph to set the balance between your initial investment (principal) and the amount you plan to deposit regularly. Your selected point shows how much you would start with and how much you would contribute over time to reach your savings goal."
  );
});

onEvent("savingsPlanOutputScreenBackButton", "click", function () {
  setScreen("savingsPlanScreen2");
});

// Event Handlers (Screen Navigation) For Savings Plan Summary Screen
onEvent("savingsPlanSummaryScreenBackButton", "click", function () {
  setScreen("savingsPlanScreen2");
});

// Event Handlers (Screen Navigation) For Find Accounts Screen 1
onEvent("findAccountsMonthlyFeesToolTip", "click", function () {
  lastScreen = getScreen();
  setText("helpScreenOutput",
    "Why Would I Want Monthly Fees? \n \n" +
    "People oftentimes choose interest-bearing accounts with monthly fees because the benefits that come with these accounts usually outweigh the cost. Accounts with monthly fees are likely to have higher interest rates, and come with special perks or features."
  );
  setScreen("helpScreen");
});

onEvent("findAccountsMinimumDepositToolTip", "click", function () {
  lastScreen = getScreen();
  setText("helpScreenOutput", 
    "Why Would I Want a Minimum Deposit? \n \n" +
    "People oftentimes choose interest-bearing accounts with a minimum deposit because the benefits that come with these accounts usually outweigh the cost. Accounts with a minimum deposit are likely to have higher interest rates, and come with access to premium account features."
  );
  setScreen("helpScreen");
});

onEvent("findAccountsScreen1BackButton", "click", function () {
  setScreen("interestScreen");
});

onEvent("findAccountsScreen1NextButton", "click", function () {
  let inputCheck = true;
  if (checkInput(getText("findAccountsPrincipalInput")) == false) {
    setText("findAccountsPrincipalInput", "Invalid Input - Must be a whole number");
    inputCheck = false
  }
  if (checkInput(getText("findAccountsInvestmentLengthInput")) == false) {
    setText("findAccountsInvestmentLengthInput", "Invalid Input - Must be a whole number");
    inputCheck = false;
  }
  if (inputCheck == true) {
    setText("findAccountsPreferredBankInput", "None");
    setScreen("findAccountsScreen2");
  }
});

// Event Handlers (Screen Navigation) For Find Accounts Screen 2
onEvent("findAccountsFixedRatesToolTip", "click", function () {
  lastScreen = getScreen();
  setText("helpScreenOutput",
    "Why Would I Want Fixed Rates? \n \n" +
    "People oftentimes choose interest-bearing accounts with fixed rates (such as CD Accounts) because these accounts come with reliable stability and proctections. Accounts with fixed rates have easily predictable growth and come with protections from rate drops."
  );
  setScreen("helpScreen");
});

onEvent("findAccountsScreen2BackButton", "click", function () {
  setScreen("findAccountsScreen1");
});

// Event Handlers (Screen Navigation) For Find Accounts Output Screen
onEvent("findAccountsOutputScreenBackButton", "click", function () {
  setScreen("findAccountsScreen2");
});

// Event Handlers (Screen Navigation) For Browse Accounts Screen 1

onEvent("browseAccountsScreen1BackButton", "click", function () {
  setScreen("interestScreen");
});

onEvent("browseAccountsCompareRatesButton", "click", function () {
  hideElement("compareRatesScreen1Tutorial");
  setScreen("browseAccountsCompareRatesScreen1");
});

// Event Handlers (Screen Navigation) For Browse Accounts Search Output Screen
onEvent("browseAccountsSearchOutputScreenBackButton", "click", function () {
  setScreen("browseAccountsScreen1");
});

// Event Handlers (Screen Navigation) For Browse Acounts All Accounts Screen
onEvent("browseAccountsAllAccountsScreenBackButton", "click", function () {
  setScreen("browseAccountsScreen1");
});

// Event Handlers (Screen Navigation) For Browse Accounts Compare Rates Screen 1
onEvent("browseAccountsCompareRatesScreen1BackButton", "click", function () {
  setScreen("browseAccountsScreen1");
});

onEvent("compareRatesScreen1ToolTip", "click", function () {
  showElement("compareRatesScreen1Tutorial");
  setText("compareRatesScreen1Tutorial",
    "On the Compare Accounts screen, you can compare two interest‑bearing accounts to see which one earns more over a chosen period of time. Enter the first account in the top box and the second account in the next box. Then enter the number of years you want to compare and the starting principal amount each account begins with. The app will show which account performs better over that time."
  );
});

// Event Handlers (Screen Navigation) For Compare Rates Output Screen
onEvent("compareRatesOutputScreenBackButton", "click", function () {
  setScreen("browseAccountsCompareRatesScreen1");
});